# Licensed Materials - Property of IBM
# Text Toolkit for IBM Streams
# (c) Copyright IBM Corp. 2019
# All rights reserved.                               


.PHONY: clean tkidx

clean:
	ant clean;

tkidx:
	ant indextoolkits;
